name: energise_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  avatar_glow: ^3.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_countdown_timer: ^4.1.0
  flutter_localizations:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  google_maps_flutter: ^2.6.1
  http: ^1.2.1
  in_app_review: ^2.0.9
  intl: any
  provider: ^6.1.2
  rating_dialog: ^2.0.4
  share_plus: ^4.0.4
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
